swagger: "2.0"
info:
  description: "The goal of the component consists in selecting the best data and computation movement actions to be adopted in order to restore the level of data quality, quality of service and security defined by the application developer."
  version: "0.0.1"
  title: "Decision System for Data and Computation Movement"
  license:
    name: "License TBD"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "TBD"
basePath: "/"
schemes:
- "http"
paths:
  /NotifyViolation:
    post:
      summary: "notifyViolation"
      description: "The method receives in input the list of violated requirements."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Violations"
        in: "body"
        schema:
          example:
            title: "Crispy schnitzel"
            text: "Prepare eggs…"

      responses:
        400:
          description: "Invalid input"
        500:
          description: "Internal error"
        200:
          description: "Input processed correctly"
          
  /AddVDC:
    post:
      summary: "add VDC"
      description: "The API is called when a new VDC is deployed, it receives in input the abstract blueprint."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ConcreteBlueprint"
        in: "body"
        schema:
          example:
            title: "Crispy schnitzel"
            text: "Prepare eggs…"
      responses:
        400:
          description: "Invalid input"
        500:
          description: "Internal error"
        200:
          description: "Input processed correctly"

              
              
              