swagger: "2.0"
info:
  description: "The goal of the component consists in selecting the best data and computation movement actions to be adopted in order to restore the level of data quality, quality of service and security defined by the application developer."
  version: "0.0.1"
  title: "Decision System for Data and Computation Movement"
  license:
    name: "License TBD"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "TBD"
basePath: "/"
schemes:
- "http"
paths:
  /NotifyViolation:
    post:
      summary: "notifyViolation"
      description: "The method receives in input the list of violated requirements."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "violations"
        description: "the List of violations"
        required: true
        schema:
          $ref: "#/definitions/violations"

      responses:
        400:
          description: "Invalid input"
        500:
          description: "Internal error"
        200:
          description: "Input processed correctly"
          
  /AddVDC:
    post:
      summary: "add VDC"
      description: "The API is called when a new VDC is deployed, it receives in input the abstract blueprint."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "ConcreteBlueprint"
        description: "Concrete blueprint of the VDC to be added"
        required: true
        schema:
          type: object
          example:
            INTERNAL_STRUCTURE:
              Overview:
                name: BP1
                description: only for testing
                tags: {}
              Data_Sources:
                - id: MinioDS1
                  class: relational database
                  type: sql
                  parameters:
                    hostname: localhost
                    port: '8000'
                    proxy-hostname: localhost
                    proxy-port: '9800'
                    username: user1
                    password: pass1
                  location: edge
                  resourceUsed:
                    - type: space
                      total: '40'
                      unit: GB
                    - type: memory
                      total: '3'
                      unit: GB
                - id: MinioDS2
                  type: sql
                  class: relational database
                  parameters:
                    hostname: localhost
                    port: '8000'
                    proxy-hostname: localhost
                    proxy-port: '9800'
                    username: user1
                    password: pass1
                  location: edge
                  resourceUsed:
                    - type: space
                      total: '20'
                      unit: GB
                    - type: memory
                      total: '5'
                      unit: GB
              Flow:
                platform: Spark
              Testing_Output_Data: {}
              resourcesAvailable:
                - name: rescource1
                  type: sql
                  location: edge
                  characteristics:
                    - type: space
                      total: '100'
                      free: '50'
                      unit: GB
                    - type: memory
                      total: '100'
                      free: '50'
                      unit: GB
                - name: rescource2
                  type: sql
                  location: edge
                  characteristics:
                    - type: space
                      total: '100'
                      free: '50'
                      unit: GB
                    - type: memory
                      total: '100'
                      free: '50'
                      unit: GB
                - name: rescource3
                  type: sql
                  location: cloud
                  characteristics:
                    - type: space
                      total: '100'
                      free: '50'
                      unit: GB
                    - type: memory
                      total: '100'
                      free: '50'
                      unit: GB
                - name: rescource4
                  type: computation
                  location: edge
                  characteristics:
                    - type: memory
                      total: '100'
                      free: '50'
                      unit: GB
                    - type: CPU
                      total: '100'
                      free: '50'
                      unit: percentage

              
            "DATA_MANAGEMENT":
              - method_id: GetAllBloodTests
                attributes:
                  dataUtility:
                    - id: availability_9599
                      description: Availability 95-99
                      type: Availability
                      properties:
                        availability:
                          unit: percentage
                          minimum: 95
                          maximum: 99
                    - id: responseTime_1
                      description: ResponseTime 1
                      type: ResponseTime
                      properties:
                        responseTime:
                          maximum: 1
                          unit: second
                    - id: volume_10000
                      description: volume 10000
                      type: Volume
                      properties:
                        volume:
                          value: '10000'
                          unit: tuple
                    - id: timeliness_06
                      description: Timeliness 0.6
                      type: Timeliness
                      properties:
                        timeliness:
                          maximum: 0.6
                          unit: NONE
                    - id: processCompleteness_90
                      description: Process completeness 90
                      type: Process completeness
                      properties:
                        completeness:
                          minimum: 90
                          unit: percentage
                    - id: scaleUpMemory
                      description: scale-up memory
                      type: Scale-up
                      properties:
                        ramGain:
                          unit: percentage
                          value: '150'
                        ramLimit:
                          unit: percentage
                          value: '95'
                    - id: scaleUpSpace
                      description: scale-up space
                      type: Scale-up
                      properties:
                        spaceGain:
                          unit: percentage
                          value: '110'
                        spaceLimit:
                          unit: percentage
                          value: '90'
                    - id: throughput_5
                      description: Throughput
                      type: Throughput
                      properties:
                        throughput:
                          maximum: 5
                          unit: Gb/s
                    - id: precision_08
                      description: Precision
                      type: Precision
                      properties:
                        precision:
                          minimum: 0.8
                          unit: none
                    - id: recall_09
                      description: Recall
                      type: Recall
                      properties:
                        recall:
                          minimum: 0.9
                          unit: none
                    - id: accuracy_09
                      description: Accuracy
                      type: Accuracy
                      properties:
                        accuracy:
                          minimum: 0.9
                          unit: none
                  security:
                    - id: encryptionAES_128
                      description: Encryption AES 128
                      type: Encryption
                      properties:
                        algorithm:
                          unit: enum
                          value: AES
                        keyLength:
                          unit: number
                          minimum: 128
                    - id: tracing_99100
                      description: Tracing
                      type: Tracing
                      properties:
                        level:
                          unit: enum
                          value: datasource
                        sampleRate:
                          unit: percentage
                          minimum: 99
                          maximum: 100
                    - id: aclRoleBasedReadOnly
                      description: ACL rolebased readOnly
                      type: ACL
                      properties:
                        kind:
                          unit: enum
                          value: rolebased
                        role:
                          unit: enum
                          value: readOnly
                    - id: encryptionAES_256
                      description: Encryption AES 256
                      type: Encryption
                      properties:
                        algorithm:
                          unit: enum
                          value: AES
                        keyLength:
                          unit: number
                          minimum: 256
                  privacy:
                    - id: purposeControlNCGovernment
                      description: PurposeControl NonCommercial Government
                      type: PurposeControl
                      properties:
                        allowedPurpose:
                          unit: enum
                          value: NonCommercial
                        allowedGuarantor:
                          unit: enum
                          value: Government
                    - id: mutationControlNCGovernment
                      description: MutationControl NonCommercial Government
                      type: MutationControl
                      properties:
                        allowedPurpose:
                          unit: enum
                          value: NonCommercial
                        allowedGuarantor:
                          unit: enum
                          value: Government

            ABSTRACT_PROPERTIES: 
              - method_id: GetAllBloodTests
                goalTrees:
                  dataUtility:
                    type: AND
                    children:
                      - type: AND
                        children:
                          - type: OR
                            leaves:
                              - id: serviceAvailable
                                description: Service available
                                weight: 1
                                attributes:
                                  - availability_9599
                              - id: serviceScalable
                                description: Service Scalable
                                weight: 1
                                attributes:
                                  - scaleUpMemory
                                  - scaleUpSpace
                          - type: OR
                            leaves:
                              - id: fastDataProcess
                                description: Fast data process
                                weight: 1
                                attributes:
                                  - responseTime_1
                              - id: fastDataStreaming
                                description: Fast data streaming
                                weight: 1
                                attributes:
                                  - throughput_5
                      - type: AND
                        leaves:
                          - id: dataVolume
                            description: Data volume
                            weight: 1
                            attributes:
                              - volume_10000
                          - id: timeliness
                            description: Timeliness
                            weight: 1
                            attributes:
                              - timeliness_06
                          - id: accuracy
                            description: Accuracy
                            weight: 1
                            attributes:
                              - accuracy_09
                          - id: completeness
                            description: Completeness
                            weight: 1
                            attributes:
                              - processCompleteness_90
                          - id: consistency
                            description: consistency
                            weight: 1
                            attributes:
                              - precision_08
                              - recall_09
                  security:
                    type: AND
                    children:
                      - type: AND
                        leaves:
                          - id: storageEncryption
                            description: Storage encryption
                            weight: 1
                            attributes:
                              - encryptionAES_128
                          - id: '11'
                            description: Data encryption
                            weight: 1
                            attributes:
                              - encryptionAES_256
                    leaves:
                      - id: accessControl
                        description: Access control
                        weight: 1
                        attributes:
                          - aclRoleBasedReadOnly
                      - id: tracing
                        description: Tracing and monitoring
                        weight: 1
                        attributes:
                          - tracing_99100
                  privacy:
                    type: AND
                    leaves:
                      - id: purposeControl
                        description: Purpose control
                        weight: 1
                        attributes:
                          - purposeControlNCGovernment
                      - id: mutationControl
                        description: Mutation control
                        weight: 1
                        attributes:
                          - mutationControlNCGovernment

            COOKBOOK_APPENDIX: {}
            EXPOSED_API: {}
      responses:
        400:
          description: "Invalid input"
        500:
          description: "Internal error"
        200:
          description: "Input processed correctly"

definitions:        
  violations:
    type: "array"
    items: 
      $ref: "#/definitions/violation"

  violation:
    type: "object"
    properties:
      vdcId:
        type: "string"
        example: "1" 
        description: "the agreement id"
      methodId: 
        type: "string"
        example: BP1 
      metrics: 
        type: "array"
        items: 
          type: "object"
          properties:
            key:
              type: "integer"
            value:
              type: "string"
            datetime:
              type: "string"
    example:
      - vdcId: osr_hospital_vdc
        methodId: getAllValuesForBloodTestComponent
        metrics:
          - key: availability
            value: 90
            datetime: '2018-08-07T10:50:23.674337517+02:00'
          - key: responseTime
            value: 1.5
            datetime: '2018-08-07T10:50:23.674337517+02:00'

              
              
              